# This Dockerfile is for building an image suitable for running catwalk's tests.
# There are no instruction lines in this Dockerfile that install catwalk. Instead, the entrypoint
# script handles installing catwalk from a particular commit at runtime, based on the environment
# variable "COMMIT_SHA". That way we don't need to rebuild and push the image each time we run
# tests, and we can be sure the dependencies are always up-to-date.
#
# To rebuild and push this image to Beaker, run 'make docker-testing'.

FROM ghcr.io/allenai/pytorch:1.13.0-cuda11.6-python3.9

COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /testing

ENTRYPOINT ["/entrypoint.sh"]
